from flask import Flask, render_template, request, jsonify

app = Flask(__name__)

# Enhanced chatbot logic with more responses and NLP support
def chatbot_response(message):
    responses = {
        "hi": "Hello! How can I assist you today?",
        "hello": "Hi there! What can I do for you?",
        "how are you": "I'm just a bot, but I'm doing great! How about you?",
        "bye": "Goodbye! Have a wonderful day!",
        "what is your name": "I'm ChatBot, your virtual assistant!",
        "tell me a joke": "Why did the scarecrow win an award? Because he was outstanding in his field!",
        "what can you do": "I can chat with you, tell jokes, and answer simple questions!",
        "who created you": "I was created by a developer who loves AI and chatbots!",
        "what is AI": "Artificial Intelligence (AI) is the simulation of human intelligence in machines that can think, learn, and solve problems!",
        "how does a chatbot work": "A chatbot processes user input, understands intent, and responds accordingly using predefined logic or AI!",
        "tell me another joke": "Why don’t skeletons fight each other? They don’t have the guts!",
        "what’s the weather like": "I don't have real-time data, but you can check a weather app for accurate updates!",
        "recommend a book": "Sure! If you like mystery, try 'The Girl with the Dragon Tattoo'. If you prefer fantasy, 'Harry Potter' is a great choice!",
        "how old are you": "I exist in the digital world, so I don’t age!",
        "where are you from": "I live in the cloud, floating between servers and data!",
        "what’s your favorite color": "I like all colors, but blue is quite nice!",
        "who is your favorite superhero": "I think Iron Man is pretty cool with all his tech!",
        "can you sing": "I wish I could! But I can tell you song lyrics if you’d like!",
        "do you like humans": "Of course! Humans are fascinating and creative beings!",
        "what is the capital of France": "The capital of France is Paris!",
        "who was Albert Einstein": "Albert Einstein was a physicist known for developing the theory of relativity!",
        "what is the tallest mountain": "Mount Everest is the tallest mountain in the world!",
        "who wrote Hamlet": "Hamlet was written by William Shakespeare!",
        "what is the speed of light": "The speed of light is approximately 299,792,458 meters per second!",
        "who invented the telephone": "Alexander Graham Bell is credited with inventing the telephone!",
        "what is 2+2": "2+2 equals 4!",
        "who discovered gravity": "Gravity was discovered by Sir Isaac Newton!",
        "what is the meaning of life": "The meaning of life is a philosophical question—some say it's 42!",
        "what is the population of Earth": "The population of Earth is over 8 billion people!",
        "how does a car engine work": "A car engine converts fuel into mechanical energy through combustion!",
        "who painted the Mona Lisa": "The Mona Lisa was painted by Leonardo da Vinci!",
        "what is photosynthesis": "Photosynthesis is the process by which plants convert sunlight into energy!",
        "who discovered electricity": "Benjamin Franklin made early discoveries about electricity!",
        "what is Python": "Python is a popular programming language known for its simplicity and versatility!",
        "how does the internet work": "The internet is a global network of computers communicating using protocols!",
        "what is the capital of Japan": "The capital of Japan is Tokyo!",
        "who is the president of the USA": "You can check the latest news to see who the current president is!",
        "what is blockchain": "Blockchain is a decentralized technology used for secure transactions!",
        "explain quantum computing": "Quantum computing uses quantum bits (qubits) to perform complex calculations much faster than classical computers!",
        "what is an atom": "An atom is the smallest unit of matter, composed of protons, neutrons, and electrons!",
        "who won the last FIFA World Cup": "You can check the latest sports news for the most recent winner!",
        "how do airplanes fly": "Airplanes fly using lift generated by their wings, which counteracts gravity!",
        "what is climate change": "Climate change refers to long-term shifts in temperature and weather patterns due to human activities!",
        "what is a black hole": "A black hole is a region in space where gravity is so strong that nothing can escape!",
        "who invented the computer": "Charles Babbage is considered the father of the computer!",
        "what is the periodic table": "The periodic table is a chart that organizes chemical elements based on their properties!",
        "how do vaccines work": "Vaccines stimulate the immune system to recognize and fight specific diseases!",
        "what is cryptocurrency": "Cryptocurrency is a digital currency secured by cryptography, such as Bitcoin!"
    }
    
    return responses.get(message.lower(), "I'm still learning! Can you ask me something else?")

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/chat', methods=['POST'])
def chat():
    user_message = request.json.get("message")
    bot_response = chatbot_response(user_message)
    return jsonify({"response": bot_response})

if __name__ == '__main__':
    app.run(debug=True)